using AIOTCA3.Entities;

namespace AIOTCA3.DataContexts.PostsMigrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<AIOTCA3.DataContexts.PostsDb>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            MigrationsDirectory = @"DataContexts\PostsMigrations";
        }

        protected override void Seed(AIOTCA3.DataContexts.PostsDb context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data. E.g.
            //
            //    context.People.AddOrUpdate(
            //      p => p.FullName,
            //      new Person { FullName = "Andrew Peters" },
            //      new Person { FullName = "Brice Lambson" },
            //      new Person { FullName = "Rowan Miller" }
            //    );
            //
            context.Posts.AddOrUpdate(
                new Post { Author = "Julian Alwandy", Body = "Lorem ipsum dolor sit amet, novum doctus vel ea, est no solum meliore invidunt. Sed paulo persius id. Sed ceteros perfecto repudiandae ne. Te nobis putant sanctus vix, suscipit tractatos scriptorem sed ut. Cu usu quas electram imperdiet, vix eu malorum accusam intellegebat. Nam no error imperdiet intellegebat, ex dicit omnes dolores vel.Ad ius fierent senserit maluisset.Ne sea dictas fierent percipit,duo apeirian adolescens exei oblique sensibus sea.Ne vix mutat graeci,elit meis quo no.At mei quis vivendo accusata.Sit ferri nulla an.Reque doctus ne sea.Pri ex amet iusto vivendo,saperet intellegat voluptaria sit ne.Et idque detracto gubergren per.Est splendide complectitur cu,ut vero putant omittam vim.Ei deserunt expetenda sea,eu dicant albucius praesent vix,nullam assentior vituperata eu has.Ei nostro facilis consequuntur eam,ad exerci senserit nec.Ad est congue conclusionemque.Sed nibh duis appetere at.Ut labitur inermis definitiones pri, ea mucius malorum sea,erant omnesque detraxit ut cum.Ne dolorem imperdiet posidonium sed, consul fuisset recusabo vel et, has vide conceptam forensibus id.Pri wisi oportere eu.No duo viderer fastidii assentior,at adhuc intellegat sea.", Date = DateTime.Now, Title = "Example post #0" },
                new Post { Author = "Julian Alwandy", Body = "Lorem ipsum dolor sit amet, novum doctus vel ea, est no solum meliore invidunt. Sed paulo persius id. Sed ceteros perfecto repudiandae ne. Te nobis putant sanctus vix, suscipit tractatos scriptorem sed ut. Cu usu quas electram imperdiet, vix eu malorum accusam intellegebat. Nam no error imperdiet intellegebat, ex dicit omnes dolores vel.Ad ius fierent senserit maluisset.Ne sea dictas fierent percipit,duo apeirian adolescens exei oblique sensibus sea.Ne vix mutat graeci,elit meis quo no.At mei quis vivendo accusata.Sit ferri nulla an.Reque doctus ne sea.Pri ex amet iusto vivendo,saperet intellegat voluptaria sit ne.Et idque detracto gubergren per.Est splendide complectitur cu,ut vero putant omittam vim.Ei deserunt expetenda sea,eu dicant albucius praesent vix,nullam assentior vituperata eu has.Ei nostro facilis consequuntur eam,ad exerci senserit nec.Ad est congue conclusionemque.Sed nibh duis appetere at.Ut labitur inermis definitiones pri, ea mucius malorum sea,erant omnesque detraxit ut cum.Ne dolorem imperdiet posidonium sed, consul fuisset recusabo vel et, has vide conceptam forensibus id.Pri wisi oportere eu.No duo viderer fastidii assentior,at adhuc intellegat sea.", Date = DateTime.Now, Title = "Example post #1" },
                new Post { Author = "Julian Alwandy", Body = "Lorem ipsum dolor sit amet, novum doctus vel ea, est no solum meliore invidunt. Sed paulo persius id. Sed ceteros perfecto repudiandae ne. Te nobis putant sanctus vix, suscipit tractatos scriptorem sed ut. Cu usu quas electram imperdiet, vix eu malorum accusam intellegebat. Nam no error imperdiet intellegebat, ex dicit omnes dolores vel.Ad ius fierent senserit maluisset.Ne sea dictas fierent percipit,duo apeirian adolescens exei oblique sensibus sea.Ne vix mutat graeci,elit meis quo no.At mei quis vivendo accusata.Sit ferri nulla an.Reque doctus ne sea.Pri ex amet iusto vivendo,saperet intellegat voluptaria sit ne.Et idque detracto gubergren per.Est splendide complectitur cu,ut vero putant omittam vim.Ei deserunt expetenda sea,eu dicant albucius praesent vix,nullam assentior vituperata eu has.Ei nostro facilis consequuntur eam,ad exerci senserit nec.Ad est congue conclusionemque.Sed nibh duis appetere at.Ut labitur inermis definitiones pri, ea mucius malorum sea,erant omnesque detraxit ut cum.Ne dolorem imperdiet posidonium sed, consul fuisset recusabo vel et, has vide conceptam forensibus id.Pri wisi oportere eu.No duo viderer fastidii assentior,at adhuc intellegat sea.", Date = DateTime.Now, Title = "Example post #2" },
                new Post { Author = "Julian Alwandy", Body = "Lorem ipsum dolor sit amet, novum doctus vel ea, est no solum meliore invidunt. Sed paulo persius id. Sed ceteros perfecto repudiandae ne. Te nobis putant sanctus vix, suscipit tractatos scriptorem sed ut. Cu usu quas electram imperdiet, vix eu malorum accusam intellegebat. Nam no error imperdiet intellegebat, ex dicit omnes dolores vel.Ad ius fierent senserit maluisset.Ne sea dictas fierent percipit,duo apeirian adolescens exei oblique sensibus sea.Ne vix mutat graeci,elit meis quo no.At mei quis vivendo accusata.Sit ferri nulla an.Reque doctus ne sea.Pri ex amet iusto vivendo,saperet intellegat voluptaria sit ne.Et idque detracto gubergren per.Est splendide complectitur cu,ut vero putant omittam vim.Ei deserunt expetenda sea,eu dicant albucius praesent vix,nullam assentior vituperata eu has.Ei nostro facilis consequuntur eam,ad exerci senserit nec.Ad est congue conclusionemque.Sed nibh duis appetere at.Ut labitur inermis definitiones pri, ea mucius malorum sea,erant omnesque detraxit ut cum.Ne dolorem imperdiet posidonium sed, consul fuisset recusabo vel et, has vide conceptam forensibus id.Pri wisi oportere eu.No duo viderer fastidii assentior,at adhuc intellegat sea.", Date = DateTime.Now, Title = "Example post #3" },
                new Post { Author = "Julian Alwandy", Body = "Lorem ipsum dolor sit amet, novum doctus vel ea, est no solum meliore invidunt. Sed paulo persius id. Sed ceteros perfecto repudiandae ne. Te nobis putant sanctus vix, suscipit tractatos scriptorem sed ut. Cu usu quas electram imperdiet, vix eu malorum accusam intellegebat. Nam no error imperdiet intellegebat, ex dicit omnes dolores vel.Ad ius fierent senserit maluisset.Ne sea dictas fierent percipit,duo apeirian adolescens exei oblique sensibus sea.Ne vix mutat graeci,elit meis quo no.At mei quis vivendo accusata.Sit ferri nulla an.Reque doctus ne sea.Pri ex amet iusto vivendo,saperet intellegat voluptaria sit ne.Et idque detracto gubergren per.Est splendide complectitur cu,ut vero putant omittam vim.Ei deserunt expetenda sea,eu dicant albucius praesent vix,nullam assentior vituperata eu has.Ei nostro facilis consequuntur eam,ad exerci senserit nec.Ad est congue conclusionemque.Sed nibh duis appetere at.Ut labitur inermis definitiones pri, ea mucius malorum sea,erant omnesque detraxit ut cum.Ne dolorem imperdiet posidonium sed, consul fuisset recusabo vel et, has vide conceptam forensibus id.Pri wisi oportere eu.No duo viderer fastidii assentior,at adhuc intellegat sea.", Date = DateTime.Now, Title = "Example post #4" },
                new Post { Author = "Julian Alwandy", Body = "Lorem ipsum dolor sit amet, novum doctus vel ea, est no solum meliore invidunt. Sed paulo persius id. Sed ceteros perfecto repudiandae ne. Te nobis putant sanctus vix, suscipit tractatos scriptorem sed ut. Cu usu quas electram imperdiet, vix eu malorum accusam intellegebat. Nam no error imperdiet intellegebat, ex dicit omnes dolores vel.Ad ius fierent senserit maluisset.Ne sea dictas fierent percipit,duo apeirian adolescens exei oblique sensibus sea.Ne vix mutat graeci,elit meis quo no.At mei quis vivendo accusata.Sit ferri nulla an.Reque doctus ne sea.Pri ex amet iusto vivendo,saperet intellegat voluptaria sit ne.Et idque detracto gubergren per.Est splendide complectitur cu,ut vero putant omittam vim.Ei deserunt expetenda sea,eu dicant albucius praesent vix,nullam assentior vituperata eu has.Ei nostro facilis consequuntur eam,ad exerci senserit nec.Ad est congue conclusionemque.Sed nibh duis appetere at.Ut labitur inermis definitiones pri, ea mucius malorum sea,erant omnesque detraxit ut cum.Ne dolorem imperdiet posidonium sed, consul fuisset recusabo vel et, has vide conceptam forensibus id.Pri wisi oportere eu.No duo viderer fastidii assentior,at adhuc intellegat sea.", Date = DateTime.Now, Title = "Example post #5" }
                );
        }
    }
}
